/*\
title: $:/plugins/welford/twstaticblog/export/get-export-image.js
type: application/javascript
module-type: macro
returns the formatted link tiddler to a tiddler
\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*
Information about this macro
*/

exports.name = "tv-get-export-image-link";

exports.params = [
];

var TAG_EXP_ATTR = "tag";
var FRAMEWORK_EXP_ATTR = "framework";
var POSTS_EXP_ATTR = "posts";
var INDEX_EXP_ATTR = "index";

var FRAMEWORK_TAG = "blog-framework";
var TAG_LINK_ATTR = "taglink";
var INDEX_POST = "index";

/*
Run the macro
*/
exports.run = function() {
	var title = this.getVariable("currentTiddler");
	var attr = this.getVariable("tv-subfolder-links");
	var path_to_root="./"	

	if(
		this.imageSource.indexOf("http:") != -1
	||	this.imageSource.indexOf("https:") != -1
	){
		return this.imageSource;
	}
	//------------------------------------------------------
	//correcting the root location based on attribute type...
	//reference the folder stucture description above for more details

	//generic blog posts are 3 layers deep
	if(attr==POSTS_EXP_ATTR){	
		path_to_root="../../../"
	}
	//autogenerated tag posts and framework stuff go in the same place for convenience [root]/tag/...
	else if(attr==TAG_EXP_ATTR){		
		path_to_root="../"			
	}
	//index.html and framework stuff are special and go in the root
	else if(attr==INDEX_EXP_ATTR || attr==FRAMEWORK_EXP_ATTR){
		path_to_root="./"	
	}
	var finalLink = path_to_root;	
	return (finalLink).toLocaleLowerCase() + this.imageSource;
};

})();